
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[331] =
    {   0,
        0,    0,    0,    0,    0,    0,  113,   89,   87,   88,
       75,   89,   81,   74,   89,   63,   64,   79,   78,   70,
       77,   73,   80,   37,   37,   71,   69,   82,   72,   83,
       86,   36,   67,   68,   84,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       65,   85,   66,   76,   87,    3,   93,   92,   93,   93,
      111,  110,  111,  109,  109,  111,  108,  108,  108,  108,
      108,  108,  108,   87,   48,    0,   40,    0,   53,   49,
       58,    0,    0,   51,   41,   54,   42,   55,   61,    0,
       38,    1,    2,   52,   38,   37,    0,   37,    0,   37,

       43,   45,   47,   46,   44,   36,   59,   36,   36,   36,
       36,   36,   36,   11,   36,   36,   36,   36,   36,   36,
       19,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   60,   50,   87,    3,   91,   90,    0,  107,
        0,  109,  109,    0,  109,    0,  108,  108,  108,  108,
      108,   99,  108,  108,  108,  108,    0,    0,   39,    0,
        0,   62,    0,   38,    2,   38,    0,   37,   56,   57,
       36,   36,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   17,   36,   20,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   36,   36,    0,

        0,  109,  106,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,    0,    0,    0,    0,    0,   38,
        0,    0,    4,   36,    6,    7,   36,   36,   36,   36,
       13,   14,   36,   36,   18,   21,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   36,   36,   33,   36,   36,
        0,    0,  108,  100,  101,  108,  108,  108,  108,  108,
      105,  108,  108,    0,    0,    0,    0,    5,    8,   36,
       36,   36,   36,   16,   36,   36,   24,   36,   36,   36,
       36,   36,   36,   31,   36,   36,   35,    0,    0,  108,
      102,  103,   97,  108,  108,  108,   96,    0,   38,   36,

       36,   12,   15,   36,   23,   25,   26,   27,   28,   29,
       36,   36,   36,   95,   98,  108,  104,   38,   36,   10,
       36,   30,   36,   36,   94,    9,   22,   32,   34,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   28,   28,   28,   29,   30,
       31,   31,   31,   31,   31,   32,   31,   31,   31,   33,
       31,   31,   31,   31,   34,   31,   31,   35,   31,   31,
       36,   37,   38,   39,   31,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   31,   49,   50,   51,   52,
       53,   54,   31,   55,   56,   57,   58,   59,   60,   61,
       62,   63,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        7,    1,    1,    1,    1,    8,    3,    7,    7,    7,
        9,    9,   10,    9,    9,    1,    3,    1,    1,    6,
        6,    7,    7,    7,    6,    9,    9,    9,    9,    9,
        9,   11,    9,   10,   11,    9,   11,    9,   11,    9,
       11,    9,    9,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[349] =
    {   0,
        0,   66,   66,   67,   85,    0,  672,  673,   70,  673,
      646,  147,  645,  145,  632,  673,  673,  643,   57,  673,
      139,  139,  144,  154,  159,  673,  673,   51,  642,   52,
      673,    0,  673,  673,  641,  607,  609,  143,  119,  116,
      132,  610,  142,  609,  617,  150,  598,  607,  605,  610,
      673,  136,  673,  673,  198,  673,  673,  673,  638,  642,
      673,  673,  186,  194,  199,    0,    0,  610,  156,  180,
      605,  597,  599,   79,  673,  193,  673,  202,  673,  673,
      673,  640,  215,  673,  673,  673,  673,  673,  673,  632,
      221,  673,    0,  673,  240,  260,  226,  204,  631,  279,

      622,  673,  673,  673,  621,    0,  673,  588,  600,  587,
      602,  589,  595,  581,  582,  579,  579,  582,  579,  576,
        0,  575,  579,  170,  577,  193,  218,  581,  574,  147,
      238,  579,  673,  673,  299,  673,  673,  673,  231,  673,
      255,  285,  257,    0,  302,  600,    0,  580,  239,  581,
      568,  250,  580,  569,  580,  576,  308,    0,  673,  320,
        0,  673,  328,  673,    0,  334,    0,  324,  673,  673,
      565,  577,  572,  560,  226,  574,  572,  568,  560,  566,
      569,    0,  555,    0,  561,  558,  547,  548,  550,  544,
      530,  528,  528,  539,  515,  517,  521,  523,  512,  351,

        0,  327,  673,  512,  511,  511,  506,  500,  507,  502,
      489,  489,  476,  473,  356,  388,  370,  497,  305,  391,
      279,  313,    0,  456,    0,    0,  437,  427,  416,  422,
        0,    0,  416,  413,    0,    0,  413,  412,  405,  417,
      407,  411,  416,  412,  410,  400,  405,    0,  392,  403,
      367,  436,  394,    0,    0,  400,  389,  398,  396,  377,
        0,  383,  382,  272,    0,  381,  318,    0,    0,  374,
      374,  378,  368,    0,  362,  354,    0,  362,  358,  357,
      341,  349,  348,    0,  339,  335,    0,  332,    0,  337,
        0,    0,    0,  323,  322,  310,    0,  394,  418,  274,

      274,    0,    0,  276,    0,    0,    0,    0,    0,    0,
      263,  253,  217,    0,    0,  220,    0,  673,  204,    0,
      169,    0,  138,  123,    0,    0,    0,    0,    0,  673,
      481,  492,  503,  509,  520,  531,  537,  546,  555,  566,
      573,  578,  584,  586,  588,  590,  592,  594
    } ;

static const flex_int16_t yy_def[349] =
    {   0,
      330,    1,  331,  331,  330,    5,  330,  330,  330,  330,
      330,  332,  330,  330,  333,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  334,  330,  330,  330,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  335,  330,  330,  336,  337,  337,  337,  337,
      337,  337,  337,  330,  330,  332,  330,  338,  330,  330,
      330,  330,  339,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  340,  330,  330,  330,  330,  330,  341,  330,

      330,  330,  330,  330,  330,  334,  330,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  330,  330,  330,  330,  330,  330,  335,  330,
      342,  330,  330,  343,  330,  336,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  332,  344,  330,  330,
      345,  330,  330,  330,  340,  330,  346,  341,  330,  330,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  335,

      347,  343,  330,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  332,  332,  330,  345,  330,  330,
      346,  348,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      335,  335,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  332,  216,  330,  348,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  334,  334,  334,  334,  335,  252,  337,
      337,  337,  337,  337,  337,  337,  337,  330,  330,  334,

      334,  334,  334,  334,  334,  334,  334,  334,  334,  334,
      334,  334,  334,  337,  337,  337,  337,  330,  334,  334,
      334,  334,  334,  334,  337,  334,  334,  334,  334,    0,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330
    } ;

static const flex_int16_t yy_nxt[741] =
    {   0,
        8,    9,   10,    9,   11,   12,    8,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       25,   26,   27,   28,   29,   30,   31,   32,   32,   32,
       32,   32,   32,   32,   32,   33,    8,   34,   35,   36,
       37,   38,   39,   40,   41,   42,   32,   43,   32,   44,
       32,   32,   32,   32,   45,   46,   47,   48,   49,   50,
       32,   32,   32,   51,   52,   53,   54,   55,   58,   58,
       85,   74,   56,   74,  101,  102,  104,  105,   59,   59,
       74,   86,   74,   60,   60,   61,   61,   62,   61,   61,
       63,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   64,   65,   65,   61,   61,   66,   61,
       61,   61,   67,   67,   67,   67,   67,   67,   67,   67,
       61,   61,   61,   61,   67,   67,   67,   68,   69,   67,
       67,   67,   70,   67,   71,   67,   67,   67,   72,   67,
       67,   67,   73,   67,   67,   67,   67,   67,   61,   61,
       61,   61,   77,   80,   87,   90,   92,   91,   91,   91,
      133,   93,  113,   88,   89,  115,  329,  116,   94,   81,
       95,  114,   96,   96,   97,   95,  117,  100,  100,  100,
      328,  118,  110,   78,  119,   98,  121,   98,   99,  111,
       98,  140,   98,  122,  195,  112,  125,  126,   77,  135,

      134,   74,  196,   98,  136,  149,  127,  150,   98,  128,
      151,   98,  142,  142,   99,  186,   98,  145,  145,  145,
      157,  157,  141,  327,  152,  143,  187,  143,  144,   78,
      143,  153,  143,  160,  160,   98,  140,   98,  189,   91,
       91,   91,   95,  143,   97,   97,   97,  326,  143,  163,
      164,  143,  164,   98,  144,  190,  143,  191,  166,  166,
      166,   98,  158,  325,  163,  164,  324,  141,  163,  164,
      164,  164,  192,  200,  200,  161,   95,   77,   96,   96,
       97,  227,  228,  163,  164,  197,  205,  198,  143,  164,
      143,   98,  209,   98,  206,   95,  323,  100,  100,  100,

      135,  210,   74,  142,  142,  136,  143,  322,   78,   98,
       98,  266,   98,   77,  143,  201,  143,   98,  143,  321,
      145,  145,  145,  220,  220,  220,  215,  215,   98,  159,
      320,  319,  266,  143,  143,  143,   98,  140,  217,  217,
      222,  219,  143,  219,   78,  266,  220,  220,  220,  317,
      266,  143,  166,  166,  166,   98,  140,   98,  143,  143,
      143,   77,  163,  164,  316,  164,  266,  315,  141,  251,
      251,  266,  140,   98,  264,  264,  143,  163,  164,  159,
      314,   98,  313,  164,  143,  288,  288,  141,   82,   82,
      312,  311,   78,   77,  298,  310,  298,  309,  308,  299,

      299,  299,  307,  141,  306,  305,  265,  265,  265,  220,
      220,  220,  299,  299,  299,  265,  265,  265,  304,  303,
      164,  302,  164,  301,   78,  300,  297,  265,  265,  265,
      265,  265,  265,  296,  295,  164,  299,  299,  299,  294,
      164,  140,  293,  292,  291,  290,  287,  318,  286,  318,
      285,  284,  283,  282,  289,  289,  289,  281,  280,  279,
      278,  277,  318,  289,  289,  289,  276,  318,  275,  274,
      273,  272,  141,  271,  270,  289,  289,  289,  289,  289,
      289,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   76,  269,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   82,  268,   82,  159,   82,   82,   82,
       82,   82,   82,   82,  106,  106,  263,  106,  106,  106,
      139,  262,  139,  139,  139,  139,  139,  139,  139,  139,
      139,  146,  261,  146,  146,  146,  146,  146,  260,  146,
      146,  146,  147,  147,  259,  147,  147,  147,   76,   76,
      258,   76,  257,  256,  255,  254,   76,   82,   82,  253,
       82,  250,  249,  248,  247,   82,  165,  246,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  168,  168,  168,
      139,  139,  245,  139,  244,  243,  242,  241,  139,  202,
      202,  216,  216,  218,  218,  221,  221,  252,  252,  267,

      267,  240,  239,  267,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  226,  225,  224,  223,  214,  213,
      212,  211,  208,  207,  204,  203,  199,  194,  193,  188,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  167,  162,  159,
      156,  155,  154,  148,  138,  137,  132,  131,  130,  129,
      124,  123,  120,  109,  108,  107,  103,   84,   83,   79,
       75,  330,    7,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330
    } ;

static const flex_int16_t yy_chk[741] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    4,
       19,    9,    2,    9,   28,   28,   30,   30,    3,    4,
       74,   19,   74,    3,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   12,   14,   21,   22,   23,   22,   22,   22,
       52,   23,   39,   21,   21,   40,  324,   40,   23,   14,
       24,   39,   24,   24,   24,   25,   40,   25,   25,   25,
      323,   41,   38,   12,   41,   24,   43,   24,   24,   38,
       25,   63,   25,   43,  130,   38,   46,   46,   76,   55,

       52,   55,  130,   24,   55,   69,   46,   69,   25,   46,
       69,   24,   64,   64,   24,  124,   25,   65,   65,   65,
       78,   78,   63,  321,   70,   64,  124,   64,   64,   76,
       65,   70,   65,   83,   83,   98,  139,   98,  126,   91,
       91,   91,   97,   64,   97,   97,   97,  319,   65,   91,
       91,   64,   91,   98,   64,  126,   65,  127,   95,   95,
       95,   98,   78,  316,   91,   91,  313,  139,   95,   95,
       91,   95,  127,  141,  141,   83,   96,  264,   96,   96,
       96,  175,  175,   95,   95,  131,  149,  131,  143,   95,
      143,   96,  152,   96,  149,  100,  312,  100,  100,  100,

      135,  152,  135,  142,  142,  135,  143,  311,  264,   96,
      100,  221,  100,  157,  143,  141,  142,   96,  142,  304,
      145,  145,  145,  219,  219,  219,  157,  157,  100,  160,
      301,  300,  221,  145,  142,  145,  100,  288,  160,  160,
      168,  163,  142,  163,  157,  222,  163,  163,  163,  296,
      267,  145,  166,  166,  166,  168,  200,  168,  202,  145,
      202,  215,  166,  166,  295,  166,  222,  294,  288,  200,
      200,  267,  251,  168,  215,  215,  202,  166,  166,  217,
      290,  168,  286,  166,  202,  251,  251,  200,  217,  217,
      285,  283,  215,  216,  266,  282,  266,  281,  280,  266,

      266,  266,  279,  251,  278,  276,  216,  216,  216,  220,
      220,  220,  298,  298,  298,  216,  216,  216,  275,  273,
      220,  272,  220,  271,  216,  270,  263,  216,  216,  216,
      216,  216,  216,  262,  260,  220,  299,  299,  299,  259,
      220,  252,  258,  257,  256,  253,  250,  299,  249,  299,
      247,  246,  245,  244,  252,  252,  252,  243,  242,  241,
      240,  239,  299,  252,  252,  252,  238,  299,  237,  234,
      233,  230,  252,  229,  228,  252,  252,  252,  252,  252,
      252,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  332,  227,  332,  332,  332,  332,  332,  332,

      332,  332,  332,  333,  224,  333,  218,  333,  333,  333,
      333,  333,  333,  333,  334,  334,  214,  334,  334,  334,
      335,  213,  335,  335,  335,  335,  335,  335,  335,  335,
      335,  336,  212,  336,  336,  336,  336,  336,  211,  336,
      336,  336,  337,  337,  210,  337,  337,  337,  338,  338,
      209,  338,  208,  207,  206,  205,  338,  339,  339,  204,
      339,  199,  198,  197,  196,  339,  340,  195,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  341,  341,  341,
      342,  342,  194,  342,  193,  192,  191,  190,  342,  343,
      343,  344,  344,  345,  345,  346,  346,  347,  347,  348,

      348,  189,  188,  348,  187,  186,  185,  183,  181,  180,
      179,  178,  177,  176,  174,  173,  172,  171,  156,  155,
      154,  153,  151,  150,  148,  146,  132,  129,  128,  125,
      123,  122,  120,  119,  118,  117,  116,  115,  114,  113,
      112,  111,  110,  109,  108,  105,  101,   99,   90,   82,
       73,   72,   71,   68,   60,   59,   50,   49,   48,   47,
       45,   44,   42,   37,   36,   35,   29,   18,   15,   13,
       11,    7,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,

      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330,
      330,  330,  330,  330,  330,  330,  330,  330,  330,  330
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[113] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main.l"
#line 2 "main.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "y.tab.h"

extern int yylineno;
void yyerror(const char *s);

int line_num = 1;
int comment_depth = 0;
#line 756 "lex.yy.c"

/* Integer Constants */
/* Floating Constants */
/* Character and String Constants */
#line 761 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define PREPROCESSOR 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 44 "main.l"


#line 986 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 331 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 673 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 47 "main.l"
{ comment_depth++; BEGIN(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 48 "main.l"
{ /* Single-line comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "main.l"
{ BEGIN(PREPROCESSOR); return PREPROCESSOR_DIR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 52 "main.l"
{ return AUTO; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 53 "main.l"
{ return BREAK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "main.l"
{ return CASE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 55 "main.l"
{ return CHAR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "main.l"
{ return CONST; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "main.l"
{ return CONTINUE; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "main.l"
{ return DEFAULT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 59 "main.l"
{ return DO; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 60 "main.l"
{ return DOUBLE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 61 "main.l"
{ return ELSE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 62 "main.l"
{ return ENUM; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 63 "main.l"
{ return EXTERN; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 64 "main.l"
{ return FLOAT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 65 "main.l"
{ return FOR; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 66 "main.l"
{ return GOTO; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 67 "main.l"
{ return IF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 68 "main.l"
{ return INT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "main.l"
{ return LONG; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "main.l"
{ return REGISTER; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "main.l"
{ return RETURN; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 72 "main.l"
{ return SHORT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "main.l"
{ return SIGNED; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "main.l"
{ return SIZEOF; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "main.l"
{ return STATIC; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "main.l"
{ return STRUCT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 77 "main.l"
{ return SWITCH; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 78 "main.l"
{ return TYPEDEF; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 79 "main.l"
{ return UNION; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 80 "main.l"
{ return UNSIGNED; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 81 "main.l"
{ return VOID; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 82 "main.l"
{ return VOLATILE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 83 "main.l"
{ return WHILE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 85 "main.l"
{ yylval.str = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 86 "main.l"
{ yylval.str = strdup(yytext); return INT_CONSTANT; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 87 "main.l"
{ yylval.str = strdup(yytext); return FLOAT_CONSTANT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 88 "main.l"
{ yylval.str = strdup(yytext); return CHAR_CONSTANT; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 89 "main.l"
{ yylval.str = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 91 "main.l"
{ return INC_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 92 "main.l"
{ return DEC_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 93 "main.l"
{ return LEFT_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 94 "main.l"
{ return RIGHT_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 95 "main.l"
{ return LE_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 96 "main.l"
{ return GE_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 97 "main.l"
{ return EQ_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 98 "main.l"
{ return NE_OP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 99 "main.l"
{ return AND_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 100 "main.l"
{ return OR_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 101 "main.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 102 "main.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 103 "main.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 104 "main.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 105 "main.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 106 "main.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "main.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "main.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 109 "main.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 110 "main.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "main.l"
{ return PTR_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 112 "main.l"
{ return ELLIPSIS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 114 "main.l"
{ return '('; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 115 "main.l"
{ return ')'; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 116 "main.l"
{ return '{'; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "main.l"
{ return '}'; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "main.l"
{ return '['; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "main.l"
{ return ']'; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "main.l"
{ return ';'; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "main.l"
{ return ','; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "main.l"
{ return ':'; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "main.l"
{ return '='; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "main.l"
{ return '.'; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "main.l"
{ return '&'; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "main.l"
{ return '!'; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "main.l"
{ return '~'; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "main.l"
{ return '-'; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 129 "main.l"
{ return '+'; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 130 "main.l"
{ return '*'; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "main.l"
{ return '/'; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "main.l"
{ return '%'; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "main.l"
{ return '<'; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "main.l"
{ return '>'; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 135 "main.l"
{ return '^'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 136 "main.l"
{ return '|'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 137 "main.l"
{ return '?'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "main.l"
{ /* Skip whitespace */ }
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 140 "main.l"
{ line_num++; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 142 "main.l"
{ fprintf(stderr, "Unrecognized character: %s at line %d\n", yytext, line_num); }
	YY_BREAK


case 90:
YY_RULE_SETUP
#line 146 "main.l"
{ comment_depth++; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 147 "main.l"
{ comment_depth--; if(comment_depth == 0) BEGIN(INITIAL); }
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 148 "main.l"
{ line_num++; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 149 "main.l"
{ /* Skip comment content */ }
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 150 "main.l"
{ fprintf(stderr, "Unterminated comment at line %d\n", line_num); return 0; }
	YY_BREAK


case 94:
YY_RULE_SETUP
#line 154 "main.l"
{ yylval.str = strdup(yytext); return PP_INCLUDE; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 155 "main.l"
{ yylval.str = strdup(yytext); return PP_DEFINE; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 156 "main.l"
{ yylval.str = strdup(yytext); return PP_UNDEF; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 157 "main.l"
{ yylval.str = strdup(yytext); return PP_IFDEF; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 158 "main.l"
{ yylval.str = strdup(yytext); return PP_IFNDEF; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 159 "main.l"
{ yylval.str = strdup(yytext); return PP_IF; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 160 "main.l"
{ yylval.str = strdup(yytext); return PP_ELIF; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 161 "main.l"
{ yylval.str = strdup(yytext); return PP_ELSE; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 162 "main.l"
{ yylval.str = strdup(yytext); return PP_ENDIF; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 163 "main.l"
{ yylval.str = strdup(yytext); return PP_ERROR; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 164 "main.l"
{ yylval.str = strdup(yytext); return PP_PRAGMA; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 165 "main.l"
{ yylval.str = strdup(yytext); return PP_LINE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 167 "main.l"
{ yylval.str = strdup(yytext); return HEADER_NAME; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 168 "main.l"
{ yylval.str = strdup(yytext); return STRING_LITERAL; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 169 "main.l"
{ yylval.str = strdup(yytext); return IDENTIFIER; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 170 "main.l"
{ yylval.str = strdup(yytext); return INT_CONSTANT; }
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 172 "main.l"
{ line_num++; BEGIN(INITIAL); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 173 "main.l"
{ /* Skip other preprocessor content */ }
	YY_BREAK

case 112:
YY_RULE_SETUP
#line 176 "main.l"
ECHO;
	YY_BREAK
#line 1626 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PREPROCESSOR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 331 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 331 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 330);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "main.l"


int yywrap() {
    return 1;
}
